name: whatsApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+12
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.1+3
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  firebase_messaging: ^7.0.3
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  ff_navigation_bar: ^0.1.5
  # image_cropper: ^1.3.1
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.24
  flutter_svg: ^0.19.1
  rxdart: ^0.24.1
  dotted_border: ^1.0.6
  async: ^2.4.2
  animated_splash_screen: ^1.0.1+2
  stream_transform: ^1.2.0
  flutter_icons: ^1.1.0
  fl_radial_menu: ^0.1.0
  font_awesome_flutter:
  vector_math:
  emoji_picker:  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1


flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/places.png"
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: "dev_assets/places_adaptive.png"
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google-logo.png
    - dev_assets/splash_screen_icon.png
    - assets/images/facebook-logo.png
    - assets/images/logo.jpg
    - assets/images/signUp.png
    - assets/images/emailVerify.png
    - assets/images/otp.jpg
    - assets/images/otp.jpg
    - assets/images/send-icon.jpg
    - assets/images/otp.svg
    - assets/images/default-image.jpg
    - assets/images/search.png
    - assets/images/send.png
    - assets/images/signIn.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
